### ISSUE TITLE
Eeek!

### ISSUE THREAD

**Issue by nickdesaulniers** [diafygi/webrtc-ips#2]
Let's see what browser vendors think?
https://bugzilla.mozilla.org/show_bug.cgi?id=1126187

**Comment by diafygi** [comment]
IP address availability in javascript is by design in WebRTC. In order to make peer-to-peer connections, you need the IP address of your peer. WebRTC prefers to make local connections if possible, which means knowing local IP addresses (as well as the fallback public IP address via STUN request).

Additionally, since WebRTC allows you to manually start a peer-to-peer connection, it has to make your possible peering IP addresses available to the local javascript envrionment. So this is by design.
